### DISCUSSION TITLE
[QUESTION] Docker Compose

### DISCUSSION THREAD

**Discussion by cryptedx** [sergi0g/cup#15] [Q&A] [answered]
Hi there,

how can I run cup with docker compose?

Thanks :-)

**Comment by sergi0g** [comment]
Hello @cryptedx ! Thanks for asking this question! Here's a very basic compose you can use:

```yaml
services:
  cup:
    image: ghcr.io/sergi0g/cup:latest # you can use another tag if you like
    restart: unless-stopped
    command: serve
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"
```

If you want to use a different port, or use the `cup.json` file, please check the [documentation](https://sergi0g.github.io/cup/docs) and convert the docker options to docker compose. If you have any questions or need help with a specific setup, please ask here!

**Reply by agrmohit** [reply]
You missed the `docker.sock` part. Here is the docker compose that works for me.

```yaml
services:
  cup:
    image: ghcr.io/sergi0g/cup
    container_name: cup
    command: -c /config/cup.json serve -p 8000
    volumes:
      - ./config/cup.json:/config/cup.json
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8000:8000
    restart: unless-stopped
```

**Reply by sergi0g** [reply]
Oh sorry you're right! I made this on the go so I missed that part. I'll update my comment. Thanks!

**Comment by cryptedx** [comment]
Thank you very much for your help guys. Unfortunately it won't start up completely. I can't access the WebUI and log does output only:

```
No log line matching the '' filter
```

I am using Portainer with Stacks. Usually I get everything running what I want but cup is doing something differnt.

This is the yaml which I am using:

```yaml
services:
  cup:
    image: ghcr.io/sergi0g/cup:latest
    restart: unless-stopped
    command: serve
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9000:9000"
```

When I run it with the docker command from the docs it runs fine. Have you tested it by yourself if it it really also working for you with compose?

Thanks

**Reply by sergi0g** [reply]
Ah I think I see the problem. You're probably running portainer on port 9000 (it's the default, along with 9443). At the same time, you're trying to use Cup on that same port. In that case the container itself should fail to start and there will obviously be no logs. The second issue in this setup is that Cup uses port 8000 by default, so you would need to pass `-p 9000` as an argument to `serve`.

**Reply by cryptedx** [reply]
Portainer is running on 9443 and 8000 that's why I want to use 9000. I can run it with this command
`$ docker run -tv /var/run/docker.sock:/var/run/docker.sock -p 9000:9000 ghcr.io/sergi0g/cup serve -p 9000`
and can access the WebUI but I am always trying to run everything with compose, that's why I asked here.

Well, I just added `-p 9000` to the config and tried it again. I could access the WebUI. Yesterday I did the same thing and it was not working! I swear :-D

I deleted the stack (compose) and recreated it with the same config. I can't access the WebUI again. SHOCK :-D

Ok what should I do now? I started over without `-p 9000`

```yaml
services:
  cup:
    image: ghcr.io/sergi0g/cup:latest
    restart: unless-stopped
    command: serve
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9000:9000"
```
and I am not able to reach the WebUI. Then again adding `-p 9000` to the yaml:

```yaml
services:
  cup:
    image: ghcr.io/sergi0g/cup:latest
    restart: unless-stopped
    command: serve -p 9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9000:9000"
```
I can reach the WebUI and log shows:
<img width="1119" alt="image" src="https://github.com/user-attachments/assets/801bf5ff-654e-4398-af84-c3f8c9308239">

This behavior is confusing my mind ;-) Any idea what that could be?
