### DISCUSSION TITLE
Using cup to monitor multiple servers ...

### DISCUSSION THREAD

**Discussion by adamshand** [sergi0g/cup#66] [Q&A] [answered]
Hey,

Just started playing with cup and wanting to use it to minor a few servers.

I have two cup containers running, one on 172.16.1.51:8901 and a second on 172.16.1.52:8901.  Both work as expected via the web interface and there are no errors in the logs.

On the .52 server, I have a config file as suggested by the example compose.yml file:

```
services:
  cup:
    image: ghcr.io/sergi0g/cup:latest
    container_name: cup
    restart: unless-stopped
    command: serve
    ports:
      - 8901:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./cfg/cup.json:/config/cup.json
```

And the contents of the config file are:

```
{
    "servers": {
        "nikau": "http://172.16.1.51:8901/"
    }
}
```

I'm not seeing any errors in the logs, but nothing for nikau (.51) is showing up in the web interface of the .52 server.

I've restarted the container, reloaded the web page ... and not sure where else to look at this point.

As a side note, there doesn't appear to be a shell inside the cup container which makes it a bit impossible to do any debugging from inside the container.  Would be helpful if the container included a basic shell.

Thanks, great project!!
