### ISSUE TITLE
[SUGGESTION] Filter Web view by "type"?

### ISSUE THREAD

**Issue by lepicodon** [sergi0g/cup#11]
Hello!

I just discovered this tool and really like it, thank you for creating this!

I was wondering what it would take to be able to filter the Web view, by clicking on the headers ("Updates available" for example) we would only see those images...

Also a question, I'm running Cup with the "serve" command via docker compose, do I need to restart the container for Cup to see changes (updated images)?

My compose.yml:
```
services:
  cup:
    image: ghcr.io/sergi0g/cup:latest
    container_name: cup
    mem_limit: 64m
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 12345:8000
    command: serve
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
```

Thank you for the help!
