### ISSUE TITLE
[FR] Official docker compose file

### ISSUE THREAD

**Issue by ioverho** [sergi0g/cup#26]
Firstly, thanks for making cup. This with newreleases.io has proven to be a much simpler and more enjoyable replacement for watchtower/what's up docker/diun.

I'd suggest support for running the cup docker container permanently, for example via docker compose. At idle the image is only using 15-25MB of memory, and has very low CPU usage. Personally, it's worth it, as it means I don't have to ssh into my server every time I want to check for updates.

It also simplifies installation, updating and usage, e.g.:
1. `docker compose up -d` vs `docker run -tv /var/run/docker.sock:/var/run/docker.sock -p 9000:9000 ghcr.io/sergi0g/cup serve -p 9000`
2. `docker compose run cup check` vs `docker run -tv /var/run/docker.sock:/var/run/docker.sock ghcr.io/sergi0g/cup check node:latest`

I've been using the following `compose.yaml` file, and it seems to works as expected:
```yaml
services:
  cup:
    image: ghcr.io/sergi0g/cup
    container_name: cup
    restart: unless-stopped
    command: -c /config/cup.json serve
    ports:
      - {$PORT}:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - {$CONFIG_LOCATION}/cup.json:/config/cup.json
```
But I'm not sure the configuration file is actually ingested. Specifically, adding `theme: "blue"` to the `.json` seems to have no effect. Using a malformed config file raises errors though: `Failed to parse config!`. Adding irrelevant options seems to have no effect. I haven't checked the other configuration options.

Potentially adding a default configuration file might also help simplify the `-c /config/cup.json` command. You would only need to add a volume map to overwrite the default.

Concretely, would it be possible to get a supported compose.yaml file? Thanks again!
