### ISSUE TITLE
[FR] Automatic information update

### ISSUE THREAD

**Issue by John710** [sergi0g/cup#40]
Add an automatic information update parameter in Docker-compose environments, possibly cron.

**Comment by sergi0g** [comment]
Hello @John710!

Automatic refreshing is something that is useful and I'll definitely consider implementing it in the future. 

Until then, you can create a cronjob to make a GET request to the `/refresh` endpoint and then retrieve the new data. To help others looking for the same, you can also create a guide on how to configure it and I'll happily include it in the docs.

Thanks for opening this issue!

**Comment by jdevera** [comment]
Thanks for the idea, I've set this up and it's working well:

```yaml
services:
  cup:
    image: ghcr.io/sergi0g/cup
    restart: unless-stopped
    container_name: cup
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: serve -p 9000

  cupdate:
    image: whefter/cron:v1.0.7
    restart: unless-stopped
    environment:
      CRON_CUP: "*/15 * * * * /usr/bin/curl -s http://cup:9000/refresh"
```
