### ISSUE TITLE
[BUG] Theme not work

### ISSUE THREAD

**Issue by Vctrsnts** [sergi0g/cup#45]
**Describe the bug**
Hi.
Using _docker compose_ with my `cup.json` with this code:
```
{
     "theme": "blue"
}
```
And the theme of cup is white. I read the documentation about this and put the same. I dont have any error in the logs.

The `docker-compose.yml` is this:

 ```
cup:
   image: ghcr.io/sergi0g/cup:latest
   container_name: cup # Optional
   restart: unless-stopped
   networks:
     - internal
   command: -c /config/cup.json serve
   volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - ${HOME}/config/cup/cup.json:/config/cup.json
   labels:
     - traefik.enable=true
     - traefik.http.services.cup.loadbalancer.server.port=8000
     - traefik.http.routers.cup.entrypoints=websecure
     - traefik.http.routers.cup-secure.middlewares=myauth@file
     - traefik.http.routers.cup.rule=Host(`${CUP_SERVER}`)
```

**System info (please complete the following information):**
 - OS: Debian Stable
 - Docker daemon version: 27.3.1
 - Cup version: latest

**Additional context**
In the server using _traefik_, and access to cup with `cups.mydomaing.duckdns.org`. The labels _traefik_ on `docker-compose.yml` is for this.
