### ISSUE TITLE
[BUG] Docker Compose fails to run.  panic in `src/structs/image.rs`

### ISSUE THREAD

**Issue by Kyle-Mendes** [sergi0g/cup#64]
**Describe the bug**
```
cup  |  INFO Starting server, please wait...
cup  | 
cup  | thread 'main' panicked at src/structs/image.rs:59:71:
cup  | index out of bounds: the len is 1 but the index is 1
cup  | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**To Reproduce**
```yml
services:
  cup:
    image: ghcr.io/sergi0g/cup:latest
    restart: unless-stopped
    command: -c /config/cup.json serve -p 9111
    ports:
      - 9111:9111
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/config
networks: {}
```

**Expected behavior**
The docker container starts!

**Screenshots**

**System info (please complete the following information):**
 - OS: Docker via Windows
 - Docker daemon version: Docker Desktop 4.38.0 (181591)
 - Cup version: `cup 3.2.0-alpha.1`

**Additional context**
Add any other info that you think may be useful here.

**Comment by Kyle-Mendes** [comment]
I've been trying to do some digging and I think the issue is some of my images don't have digests:

```
$ docker images --digests

REPOSITORY                TAG       DIGEST      IMAGE ID       CREATED         SIZE
cyfershepard/jellystat   latest    <none>      cc634936b692   55 years ago    224MB
```

This seems to cause the following line:

https://github.com/sergi0g/cup/blob/ffd4d6267c277bbefbcb21d847d605b89fb78d63/src/structs/image.rs#L59

To break because there is nothing to split.  A simple fix is probably to check if the array has been populated before continuing to try to get values from it.

In the mean time I'm trying to figure out why this doesn't have a digest and if I can fix that

**Comment by mihakrumpestar** [comment]
Strange, the specified image works for me (Docker Swarm). Altho I am on Linux.

**Comment by sergi0g** [comment]
Hi @Kyle-Mendes! Thanks for opening this issue. I'll try to take a look tomorrow. Images without digests should be skipped and I think I know what caused the issue. This shouldn't have been released as latest, but I made a mistake in the workflow so now everyone is running a broken version (although breakage is pretty rare).

**Comment by sergi0g** [comment]
@Kyle-Mendes I'm not able to reproduce this bug even though I also have an image without a digest locally. This observation might be leading us in the wrong direction. Can you please try to reproduce the bug with the image `ghcr.io/sergi0g/cup:v3.1.0`? Additionally, running the latest version with `command -d -c /config/cup.json serve -p 9111` and posting the logs with sensitive information redacted (e.g. API tokens) might also help debug the issue.

**Comment by Kyle-Mendes** [comment]
```yml
services:
  cup:
    image: ghcr.io/sergi0g/cup:v3.1.0
    restart: unless-stopped
    command: -d -c /config/cup.json serve -p 9111
    ports:
      - 9111:9111
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/config
networks: {}
```

Output:

```
cup-cup-1 | INFO Starting server, please wait...
cup-cup-1 | DEBUG Retrieving images to be checked
cup-cup-1 |
cup-cup-1 | thread 'main' panicked at src/structs/image.rs:56:71:
cup-cup-1 | index out of bounds: the len is 1 but the index is 1
cup-cup-1 | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
cup-cup-1 exited with code 0
```
