### ISSUE TITLE
[BUG] ERROR GET https://nvcr.io/proxy_auth

### ISSUE THREAD

**Issue by doomedramen** [sergi0g/cup#69]
I am running via docker compose.

```
services:
  cup:
    image: ghcr.io/sergi0g/cup:latest
    container_name: cup # Optional
    restart: unless-stopped
    command: serve
    ports:
      - 8076:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
networks: {}
```

when I try to start it, it gives this error on loop:

```
cup  |  INFO Starting server, please wait...
cup exited with code 0
cup  | ERROR GET https://nvcr.io/proxy_auth?&scope=&scope=repository:nvidia/hpc-benchmarks:pull: Unexpected error: {"type":"about:blank","title":"Internal Server Error","status":500,"instance":"/token"}
cup  |  INFO Starting server, please wait...
```
